/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mutfak;

import Yonetim.YonetimEkrani;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sqlsorgular.siparis;
import sqlsorgular.stoklar;

/**
 *
 * @author ozkan
 */
public class MutfakEkrani extends javax.swing.JFrame {

    /**
     * Creates new form MutfakEkrani
     */
    public MutfakEkrani() {
        initComponents();
        SiparisAl();
        this.setTitle("MUTFAK");
            //----ToolTip Kodları-----
        
        onaylaButon.setToolTipText("Onayla"); 
        reddetButon.setToolTipText("Reddet");
    }
    public void SiparisAl(){
       
        List<sqlsorgular.siparis> siparisgetirildi = new ArrayList<>();
            try{
                siparisgetirildi = new mutfakthread().siparisdene();
            }catch(Exception e){
                Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, e);
            }
            DefaultTableModel tablo =(DefaultTableModel)jTable1.getModel();
            tablo.setRowCount(0);
            
            Vector[] v = new Vector[siparisgetirildi.size()];
            for(int n=0;n<siparisgetirildi.size();n++){
                v[n] = new Vector();
                v[n].add(siparisgetirildi.get(n).getSiparis_no());
                v[n].add(siparisgetirildi.get(n).getMasa_no());
                v[n].add(siparisgetirildi.get(n).getUrun_adi());
                v[n].add(siparisgetirildi.get(n).getAdet());
                v[n].add(siparisgetirildi.get(n).getNot());
                //tablo.setValueAt(v[n], n-1, 0);
                tablo.insertRow(0,v[n]);
                //tablo.fireTableRowsInserted(v[n].size()-1, v[n].size()-1);
                    //System.out.println("vektor");
            }
            jTable1.setModel(tablo);
            jTable1.repaint();
            jTable1.revalidate();
            jTable1.getUpdateSelectionOnSort();
            this.repaint();
            this.revalidate();
            this.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Kapatma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        onaylaButon = new javax.swing.JButton();
        reddetButon = new javax.swing.JButton();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Siparis Numarası", "Masa Numarası", "Siparisler", "Adet", "Ek Özellikler"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1250, -1));

        Kapatma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kapatma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KapatmaMouseClicked(evt);
            }
        });
        getContentPane().add(Kapatma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 60, 50));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        Label.setFont(new java.awt.Font("Calibri", 1, 55)); // NOI18N
        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setText("Mutfak Ekranı");
        getContentPane().add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        onaylaButon.setBackground(java.awt.Color.green);
        onaylaButon.setText("ONAYLA");
        onaylaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaButonActionPerformed(evt);
            }
        });
        getContentPane().add(onaylaButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 146, 50));

        reddetButon.setBackground(java.awt.Color.red);
        reddetButon.setText("REDDET");
        reddetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reddetButonActionPerformed(evt);
            }
        });
        getContentPane().add(reddetButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 146, 50));

        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/yonetimBos.png"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, -1));

        setSize(new java.awt.Dimension(1279, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
      
    }//GEN-LAST:event_formMouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            SiparisCagir();
        } catch (SQLException ex) {
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void onaylaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaButonActionPerformed
        sqlsorgular.siparis s=new siparis();
        int row =jTable1.getSelectedRow();
        String siparis_no =(String)jTable1.getModel().getValueAt(row, 0); 
        String masa_no = (String)jTable1.getModel().getValueAt(row, 1);
        String urunadi= (String)jTable1.getModel().getValueAt(row, 2);
        int adet = (int) jTable1.getModel().getValueAt(row, 3);
        String ozellik = (String)jTable1.getModel().getValueAt(row, 4);
        System.out.println(urunadi);
        int urun_kod=0;
        try {
            urun_kod= s.urunkoduGetir(urunadi);
            
        } catch (SQLException ex) {
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        int idsiparis=0;
        try {
            idsiparis = s.siparisid_Bul(siparis_no, masa_no, urun_kod, adet);
        } catch (SQLException ex) {
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
             
        }
        boolean durum=false;
        try{
            durum = s.siparisSil(idsiparis);
            if(durum){
                DefaultTableModel tablo =(DefaultTableModel)jTable1.getModel();
                (tablo).removeRow(jTable1.convertRowIndexToModel(row));
                new stoklar().StokAzalt(urun_kod, adet);
                new stoklar().StokLogKaydet(urun_kod, adet, "REMOVE");
                
            }else{
                 JOptionPane.showMessageDialog(this, "Silinirken hata oldu");
             }
        }catch(SQLException ex){
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onaylaButonActionPerformed

    private void reddetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reddetButonActionPerformed
        sqlsorgular.siparis s=new siparis();
        int row =jTable1.getSelectedRow();
        String siparis_no =(String)jTable1.getModel().getValueAt(row, 0); 
        String masa_no = (String)jTable1.getModel().getValueAt(row, 1);
        String urunadi= (String)jTable1.getModel().getValueAt(row, 2);
        int adet = (int) jTable1.getModel().getValueAt(row, 3);
        String ozellik = (String)jTable1.getModel().getValueAt(row, 4);
       
        int urun_kod=0;
        try {
            urun_kod= s.urunkoduGetir(urunadi);
        } catch (SQLException ex) {
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        int idsiparis=0;
        try {
            idsiparis = s.siparisid_Bul(siparis_no, masa_no, urun_kod, adet);
        } catch (SQLException ex) {
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
             
        }
        boolean durum=false;
        try{
            durum = s.siparisReddet(idsiparis);
            if(durum){
                DefaultTableModel tablo =(DefaultTableModel)jTable1.getModel();
                (tablo).removeRow(jTable1.convertRowIndexToModel(row));
                
            }else{
                 JOptionPane.showMessageDialog(this, "Rededilirken hata oldu");
             }
        }catch(SQLException ex){
            Logger.getLogger(MutfakEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reddetButonActionPerformed

    private void KapatmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KapatmaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_KapatmaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        YonetimEkrani yonetim = new YonetimEkrani();
        this.dispose();
        yonetim.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    
    public void SiparisCagir() throws SQLException{
        sqlsorgular.siparis sid = new siparis();
        if(jTable1.getRowCount()<sid.siparisidAl() ){
            SiparisAl();
            jTable1.repaint();
            jTable1.revalidate();
            this.repaint();
            this.revalidate();
           
        }
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MutfakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MutfakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MutfakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MutfakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MutfakEkrani().setVisible(true);
                Mutfak.Timerdeneme td = new Timerdeneme();
                Timer time =new Timer();
               
                time.schedule(td,0, 20000);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kapatma;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton onaylaButon;
    private javax.swing.JButton reddetButon;
    // End of variables declaration//GEN-END:variables
}
