/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Yonetim;

import GarsonEkrani.Masalar;
import Listeners.MasalarActionListener;
import java.awt.Color;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Panel;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author ozkan
 */
public class KasaAnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form KasaAnaSayfa
     */
    public KasaAnaSayfa() {
        initComponents();
        KasaAcilis();
        sqlsorgular.ortalametod ortala = new sqlsorgular.ortalametod();
        ortala.Ekranoralama(this, this.getWidth(), this.getHeight());
        int ekrangenislik=(int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int ekranyukseklik=(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setSize(ekrangenislik,ekranyukseklik);
        this.setTitle("KASA");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(java.awt.Color.white);

        jMenu1.setText("Yönetim");

        jMenuItem1.setText("Yönetici Sayfasına Giriş");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Veritabanı Bağlantı Ayarları");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(" Hakkında");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int Masa_No;
    public HashMap<Integer, String> MasaNoAd;
    static boolean Yenile;
    Adisyon adisyon1 = new Adisyon();

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        KasaAcilis();
    }//GEN-LAST:event_formComponentShown

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFrame jfm = new JFrame();
        YonetimEkrani yonetim = new YonetimEkrani();
        yonetim.setVisible(true);
        yonetim.pack();
        yonetim.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            GirisEkrani.ayarEkrani ayar = new GirisEkrani.ayarEkrani();
            ayar.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            ayar.pack();
            ayar.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(KasaAnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        System.out.println("yeni" + adisyon1.kapat);
        Timer time = new Timer();
        TimerTask tims = new TimerTask() {
            @Override
            public void run() {
                KasaAcilis();
            }
        };
        time.schedule(tims, 0, 20000);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public void KasaAcilis() { //KasaAnaSayfa.java ekrani açıklığında çalışacak metot
        Yenile = false;
        MasaNoAd = new HashMap<>();
        Image background = Toolkit.getDefaultToolkit().createImage("masalarArkaplan.png");
        ActionListener MasaAction = new Listeners.KasaMasalarAction(); //Ekrandaki masaların actionlisteneri 
        sqlsorgular.masalar masa = new sqlsorgular.masalar();
        int adet = 0;
        try {
            adet = masa.MasaAdet(); //Masa adeti alındı
        } catch (SQLException ex) {
            Logger.getLogger(Masalar.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<sqlsorgular.masalar> masaAdlari = null; //Masa adlarini tutmak için bir liste oluşturuldu
        try {
            masaAdlari = new sqlsorgular.masalar().MasaAdlari(); //Veritabanından alınan masa adları listeye atandı
        } catch (SQLException ex) {
            Logger.getLogger(Masalar.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Integer> doluMasalar = new ArrayList<>(); //Dolu masalarin listesini tutmak için bir liste oluşturuluyor
        doluMasalar = null;
        try {
            doluMasalar = new sqlsorgular.masalar().MusaitMasalar(); //Dolu masalarin listesi doluMasalar listesine atanıyor
        } catch (SQLException ex) {
            Logger.getLogger(KasaAnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPanel jpa = new JPanel(new GridLayout(5, 5));
        for (int i = 0; i < adet; i++) { //Masa adeti kadar dönen döngü
            JButton btn = new JButton(String.valueOf(masaAdlari.get(i).getMasa_Adi())); //Veritabanından çektiğimiz isimler
            int masano = masaAdlari.get(i).getMasa_No();
            MasaNoAd.put(masano, masaAdlari.get(i).getMasa_Adi());
            btn.setPreferredSize(new Dimension(150, 50));
            btn.addActionListener(MasaAction);
            for (int j = 0; j < doluMasalar.size(); j++) {
                if (doluMasalar.get(j) == masano) {
                    btn.setBackground(Color.red);
                }
            }
            jpa.add(btn, LEFT_ALIGNMENT);
            jpa.repaint();
            jpa.revalidate();

        }

        jpa.setSize(jPanel1.getSize());
        jPanel1.remove(this);
        jPanel1.removeAll();
        jPanel1.add(jpa);
        jPanel1.validate();
        jPanel1.repaint();
        jPanel1.revalidate();
        this.repaint();
        this.revalidate();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasaAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasaAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasaAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasaAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KasaAnaSayfa kasa = new KasaAnaSayfa();
                kasa.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                kasa.setTitle("KASA");
                kasa.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
