/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GarsonEkrani;


import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JToggleButton;

/**
 *
 * @author ozkan
 */
public class UrunOzellikler extends javax.swing.JFrame {

    /**
     * Creates new form UrunOzellikler
     */
    public UrunOzellikler() {
        initComponents();
        this.setTitle("Ürün Özellik");
         sqlsorgular.ortalametod ortala = new sqlsorgular.ortalametod();
        ortala.Ekranoralama(this, this.getWidth(), this.getHeight());
        
        //----ToolTip Kodları-----
        
        Azalt.setToolTipText("Azalt"); 
        Arttir.setToolTipText("Artır");
        Not.setToolTipText("Not yaz");
        Onayla.setToolTipText("Onayla");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UrunAdiJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Arttir = new javax.swing.JButton();
        AdetTxt = new javax.swing.JTextField();
        Azalt = new javax.swing.JButton();
        ozellikPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Not = new javax.swing.JTextField();
        Onayla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(597, 564));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        UrunAdiJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UrunAdiJLabel.setText("Ürün Adı");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Adet");

        Arttir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Arttir.setText("+");
        Arttir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArttirActionPerformed(evt);
            }
        });

        AdetTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdetTxt.setText("0");

        Azalt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Azalt.setText("-");
        Azalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzaltActionPerformed(evt);
            }
        });

        ozellikPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ekstra Özellikler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        ozellikPanel.setMaximumSize(new java.awt.Dimension(560, 200));
        ozellikPanel.setPreferredSize(new java.awt.Dimension(560, 200));

        javax.swing.GroupLayout ozellikPanelLayout = new javax.swing.GroupLayout(ozellikPanel);
        ozellikPanel.setLayout(ozellikPanelLayout);
        ozellikPanelLayout.setHorizontalGroup(
            ozellikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ozellikPanelLayout.setVerticalGroup(
            ozellikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Not");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Not, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Not, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Onayla.setBackground(new java.awt.Color(0, 204, 0));
        Onayla.setText("ONAYLA");
        Onayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnaylaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(Azalt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arttir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ozellikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(UrunAdiJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(Onayla, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(UrunAdiJLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Arttir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Azalt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ozellikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Onayla, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int UrunKoduOzellik;
    ArrayList<String> OzellikListe;
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
      //  ozellikPanel.setLayout(new GridLayout(2,10)); 
        // ozellikPanel.setPreferredSize(new Dimension(400,200));
    }//GEN-LAST:event_formComponentShown

    private void ArttirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArttirActionPerformed
        // TODO add your handling code here:
        int sayi = Integer.parseInt(AdetTxt.getText().trim());
        AdetTxt.setText(String.valueOf(sayi+1));
        System.out.println(sayi);
        AdetTxt.repaint();
    }//GEN-LAST:event_ArttirActionPerformed

    private void AzaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzaltActionPerformed
        // TODO add your handling code here:
        int sayi = Integer.parseInt(AdetTxt.getText().trim());
        if(sayi<=1){
            sayi=2;
        }
        AdetTxt.setText(String.valueOf(sayi-1));
        AdetTxt.repaint();
    }//GEN-LAST:event_AzaltActionPerformed

    private void OnaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnaylaActionPerformed
        // TODO add your handling code here:
        GarsonEkrani.SiparisEkrani siparis = new GarsonEkrani.SiparisEkrani();
        OnaylaButon(UrunKoduOzellik);
       // siparis.SiparisTablosunaEkle();
       // siparis.SiparisListesi.validate();
        //siparis.SiparisListesi.repaint();
        this.setVisible(false);
       // siparis.repaint();
    }//GEN-LAST:event_OnaylaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunOzellikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunOzellikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunOzellikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunOzellikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunOzellikler().setVisible(true);
            }
        });
    }
    public void OzellikEkle(List<sqlsorgular.urunler> ozellikList){
        // ozellikPanel.setLayout(new GridLayout()); 
        this.setTitle("Ürün Özellik");
       OzellikListe = new ArrayList<>();
         ozellikPanel.setPreferredSize(new Dimension(560,200));
         AdetTxt.setText("1");
        if(ozellikList.size()>0){
           
            ozellikPanel.removeAll();
            ozellikPanel.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            for(int i = 0; i<ozellikList.size();i++){
              JToggleButton toggle = new JToggleButton(ozellikList.get(i).getOzellik_adi());
              toggle.setPreferredSize(new Dimension(50, 50));
              toggle.setMaximumSize(new Dimension(50,50));
              toggle.setSize(50,50);
              toggle.setMinimumSize(new Dimension(50,50));
              toggle.addActionListener(new ActionListener() {
                  @Override
                  public void actionPerformed(ActionEvent e) {
                      JToggleButton ozelButon = (JToggleButton) e.getSource();
                      if(ozelButon.isEnabled()){
                          OzellikListe.add(ozelButon.getText());
                      }
                      else if(!ozelButon.isEnabled()){
                          OzellikListe.remove(ozelButon.getText());
                      }
                  }
              });   
              ozellikPanel.add(toggle);
              ozellikPanel.repaint();
              ozellikPanel.revalidate();
            } 
            ozellikPanel.repaint();
        }
    }
    public void OnaylaButon(int urunKodu){
        int adet;
        adet = Integer.parseInt(AdetTxt.getText().trim());
        String not;
        not = Not.getText().trim();
        GarsonEkrani.SiparisEkrani siparis = new GarsonEkrani.SiparisEkrani();
        
        siparis.urun_Adi=UrunAdiJLabel.getText().trim();
        siparis.urun_Adet=adet;
        siparis.urun_Ozellik=OzellikListe;
        siparis.UrunKodList.add(UrunKoduOzellik);
        System.out.println("Ozellik formu"+siparis.urun_Adet+siparis.urun_Adi);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AdetTxt;
    private javax.swing.JButton Arttir;
    private javax.swing.JButton Azalt;
    private javax.swing.JTextField Not;
    private javax.swing.JButton Onayla;
    public javax.swing.JLabel UrunAdiJLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel ozellikPanel;
    // End of variables declaration//GEN-END:variables
}
